In [54]:
import pandas as pd

# data = pd.read_csv("../data/raw/empleados_sinteticos.csv", index_col="id")
data = pd.read_csv("../data/raw/empleados_sinteticos.csv")
data = data.sort_values(by='codigo_contrato', ascending=True).reset_index(drop=True)
data.head(5)

,id,nombre,fecha_ingreso,edad,sexo,fecha_retiro,cargo,codigo_contrato
0,1100007886,Trabajador_1100007886,2020-01-01,34,F,2021-06-11,Analista,100000
1,1100045791,Trabajador_1100045791,2020-01-01,39,F,2022-12-23,Gerente,100001
2,1100014532,Trabajador_1100014532,2020-01-01,27,M,2020-02-10,Consultor,100002
3,1100033415,Trabajador_1100033415,2020-01-01,41,F,2021-09-18,Consultor,100003
4,1100002152,Trabajador_1100002152,2020-01-01,55,F,2022-05-09,Consultor,100004

In [55]:
data.describe()

                 id          edad  codigo_contrato
count  5.000000e+04  50000.000000     50000.000000
mean   1.100025e+09     41.432120    124999.500000
std    1.443390e+04     13.882974     14433.901067
min    1.100000e+09     18.000000    100000.000000
25%    1.100012e+09     29.000000    112499.750000
50%    1.100025e+09     41.000000    124999.500000
75%    1.100037e+09     53.000000    137499.250000
max    1.100050e+09     65.000000    149999.000000

In [56]:
data.groupby("cargo").mean(numeric_only=True)

                       id       edad  codigo_contrato
cargo
Analista     1.100025e+09  41.262741    124774.745612
Auxiliar     1.100025e+09  41.285169    125063.826382
Consultor    1.100025e+09  41.523789    125149.428776
Coordinador  1.100025e+09  41.459800    124791.578140
Director     1.100025e+09  41.603902    125025.883206
Gerente      1.100025e+09  41.420782    124999.839484
Ingeniero    1.100025e+09  41.465738    125195.826462

In [57]:
# Ordeno columnas
# orden = ["nombre", "edad", "sexo", 'codigo_contrato', 'cargo', 'fecha_ingreso', 'fecha_retiro']

# data = data[orden]
# data

# o tambien puedo
data = data.iloc[:, [0, 1, 3, 4, 7, 6, 2, 5]]
data.head(5)

,id,nombre,edad,sexo,codigo_contrato,cargo,fecha_ingreso,fecha_retiro
0,1100007886,Trabajador_1100007886,34,F,100000,Analista,2020-01-01,2021-06-11
1,1100045791,Trabajador_1100045791,39,F,100001,Gerente,2020-01-01,2022-12-23
2,1100014532,Trabajador_1100014532,27,M,100002,Consultor,2020-01-01,2020-02-10
3,1100033415,Trabajador_1100033415,41,F,100003,Consultor,2020-01-01,2021-09-18
4,1100002152,Trabajador_1100002152,55,F,100004,Consultor,2020-01-01,2022-05-09

In [58]:
data.dtypes

id                  int64
nombre             object
edad                int64
sexo               object
codigo_contrato     int64
cargo              object
fecha_ingreso      object
fecha_retiro       object
dtype: object

In [59]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               50000 non-null  int64
 1   nombre           50000 non-null  object
 2   edad             50000 non-null  int64
 3   sexo             50000 non-null  object
 4   codigo_contrato  50000 non-null  int64
 5   cargo            50000 non-null  object
 6   fecha_ingreso    50000 non-null  object
 7   fecha_retiro     23180 non-null  object
dtypes: int64(3), object(5)
memory usage: 3.1+ MB

In [60]:
data['fecha_ingreso'] = pd.to_datetime(data['fecha_ingreso'])
data['fecha_retiro'] = pd.to_datetime(data['fecha_retiro'])

In [61]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               50000 non-null  int64
 1   nombre           50000 non-null  object
 2   edad             50000 non-null  int64
 3   sexo             50000 non-null  object
 4   codigo_contrato  50000 non-null  int64
 5   cargo            50000 non-null  object
 6   fecha_ingreso    50000 non-null  datetime64[ns]
 7   fecha_retiro     23180 non-null  datetime64[ns]
dtypes: datetime64[ns](2), int64(3), object(3)
memory usage: 3.1+ MB

### Para limpiar datos usar:
1. Filas con valores vacíos (NaN o None)
```python
# Todas las filas que tengan al menos un NaN/None
df[df.isnull().any(axis=1)]

# O solo en una columna específica (ejemplo: fecha_retiro)
df[df["fecha_retiro"].isnull()]
```

2. Fechas incorrectas
```python
# Intentar convertir a datetime y marcar errores como NaT
df["fecha_ingreso"] = pd.to_datetime(df["fecha_ingreso"], errors="coerce")

# Filas con fechas inválidas (NaT)
df[df["fecha_ingreso"].isna()]
```

3. Números duplicados
```python
# Filas duplicadas en codigo_contrato
df[df["codigo_contrato"].duplicated(keep=False)]

# o ver todo el df con filas duplicadas
df[df.duplicated(keep=False)]
```

4. para limpiar
```python
df = df.dropna()              # elimina filas con NaN
df = df.drop_duplicates()     # elimina filas duplicadas

# reemplazar manualmente valores incorrectos por nulos en fechas
df.loc[df["fecha_ingreso"] < "2020-01-01", "fecha_ingreso"] = pd.NaT
```

In [62]:
data

,id,nombre,edad,sexo,codigo_contrato,cargo,fecha_ingreso,fecha_retiro
0,1100007886,Trabajador_1100007886,34,F,100000,Analista,2020-01-01,2021-06-11
1,1100045791,Trabajador_1100045791,39,F,100001,Gerente,2020-01-01,2022-12-23
2,1100014532,Trabajador_1100014532,27,M,100002,Consultor,2020-01-01,2020-02-10
3,1100033415,Trabajador_1100033415,41,F,100003,Consultor,2020-01-01,2021-09-18
4,1100002152,Trabajador_1100002152,55,F,100004,Consultor,2020-01-01,2022-05-09
...,...,...,...,...,...,...,...,...
49995,1100009543,Trabajador_1100009543,25,M,149995,Gerente,2025-12-28,NaT
49996,1100016962,Trabajador_1100016962,19,M,149996,Analista,2025-12-28,NaT
49997,1100046004,Trabajador_1100046004,51,F,149997,Ingeniero,2025-12-28,NaT
49998,1100027829,Trabajador_1100027829,55,M,149998,Auxiliar,2025-12-28,NaT
49999,1100047187,Trabajador_1100047187,38,F,149999,Analista,2025-12-28,NaT