In [6]:
import pandas as pd

data = pd.read_csv("../data/raw/empleados_sinteticos.csv", index_col="id")
df = pd.read_csv("../data/raw/dataset.csv", index_col="id")

In [7]:
data

                 nombre fecha_ingreso  edad sexo fecha_retiro        cargo
id
1          Trabajador_1    2025-06-03    33    M          NaN    Ingeniero
2          Trabajador_2    2023-01-04    38    M   2025-02-27     Director
3          Trabajador_3    2025-08-04    32    F          NaN    Consultor
4          Trabajador_4    2024-07-13    60    M          NaN      Gerente
5          Trabajador_5    2024-05-05    21    M   2024-11-09    Consultor
...                 ...           ...   ...  ...          ...          ...
49996  Trabajador_49996    2021-08-26    18    F   2022-12-17     Auxiliar
49997  Trabajador_49997    2021-12-15    61    M   2022-05-23     Director
49998  Trabajador_49998    2024-04-06    44    F          NaN  Coordinador
49999  Trabajador_49999    2022-11-22    63    M   2024-10-10     Analista
50000  Trabajador_50000    2024-01-12    40    F   2025-03-05  Coordinador

[50000 rows x 6 columns]

In [8]:
data.describe()

               edad
count  50000.000000
mean      41.466300
std       13.842758
min       18.000000
25%       29.000000
50%       41.000000
75%       53.000000
max       65.000000

In [17]:
df_limpios = df.dropna()
df_limpios

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378
183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129
183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,BRASIL,mateusmartins,982.0,1822
183727,80's & friends! ✈️,158.0,40.0,22.0,ECUADOR,leonardokuffo,389.0,258
183729,OnePlus 8 international giveaway classifies,198.0,82.0,26.0,MEXICO,pedrojuarez,12.0,129
183730,Here it is.. Retweet this desperate,272.0,92.0,29.0,BRASIL,mateusmartins,982.0,1822
183731,Great to advertise during the year I tweeted a...,43.0,111.0,8.0,BRASIL,mateusmartins,982.0,1822
183732,Its been in love with the game with the origin...,349.0,44.0,19.0,BRASIL,mateusmartins,982.0,1822
183733,Programming is the best!,467.0,69.0,10.0,ECUADOR,leonardokuffo,389.0,258
183734,I cannot believe this!,50.0,24.0,22.0,ECUADOR,leonardokuffo,389.0,258
183735,Buy this product NOW!!,418.0,24.0,2.0,MEXICO,gabrielcarvajal,21.0,2721
183736,I have one is best color gradients: Just relea...,361.0,92.0,1.0,MEXICO,pedrojuarez,12.0,129
183737,PIC!!,346.0,115.0,24.0,BRASIL,lucasperes,82.0,351
183738,hmmm feeling bad today,296.0,93.0,29.0,MEXICO,gabrielcarvajal,21.0,2721
183739,not feeling god right now,315.0,26.0,10.0,ECUADOR,galocastillo,332.0,378
183740,Programming is a hot topic!,133.0,145.0,15.0,BRASIL,lucasperes,82.0,351
183741,Programming? i love it!,92.0,146.0,1.0,ECUADOR,galocastillo,332.0,378
183742,WHAT???,255.0,73.0,17.0,ECUADOR,galocastillo,332.0,378
183743,Amazing video by Leonardo!,432.0,95.0,18.0,BRASIL,lucasperes,82.0,351
183745,There is nothing better than programming!,424.0,110.0,29.0,BRASIL,lucasperes,82.0,351
183746,BORED AF,488.0,28.0,27.0,MEXICO,gabrielcarvajal,21.0,2721
183747,I do not know if i like programming or other t...,318.0,58.0,20.0,BRASIL,isabelladasilva,928.0,9918

In [19]:
# df_filtrado = df.fillna(0)
df_filtrado = df.fillna({"retweets":0, "mentions":-1})
df_filtrado

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,0.0,10.0,ECUADOR,leonardokuffo,389.0,258
183722,Today we commemorate and MNML Case.,500.0,21.0,-1.0,BRASIL,mateusmartins,982.0,1822
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378
183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129
183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,BRASIL,mateusmartins,982.0,1822
183727,80's & friends! ✈️,158.0,40.0,22.0,ECUADOR,leonardokuffo,389.0,258
183728,Thank you guess how did I feel somewhat offend...,NaN,50.0,10.0,MEXICO,pedrojuarez,12.0,129
183729,OnePlus 8 international giveaway classifies,198.0,82.0,26.0,MEXICO,pedrojuarez,12.0,129
183730,Here it is.. Retweet this desperate,272.0,92.0,29.0,BRASIL,mateusmartins,982.0,1822
183731,Great to advertise during the year I tweeted a...,43.0,111.0,8.0,BRASIL,mateusmartins,982.0,1822
183732,Its been in love with the game with the origin...,349.0,44.0,19.0,BRASIL,mateusmartins,982.0,1822
183733,Programming is the best!,467.0,69.0,10.0,ECUADOR,leonardokuffo,389.0,258
183734,I cannot believe this!,50.0,24.0,22.0,ECUADOR,leonardokuffo,389.0,258
183735,Buy this product NOW!!,418.0,24.0,2.0,MEXICO,gabrielcarvajal,21.0,2721
183736,I have one is best color gradients: Just relea...,361.0,92.0,1.0,MEXICO,pedrojuarez,12.0,129
183737,PIC!!,346.0,115.0,24.0,BRASIL,lucasperes,82.0,351
183738,hmmm feeling bad today,296.0,93.0,29.0,MEXICO,gabrielcarvajal,21.0,2721
183739,not feeling god right now,315.0,26.0,10.0,ECUADOR,galocastillo,332.0,378
183740,Programming is a hot topic!,133.0,145.0,15.0,BRASIL,lucasperes,82.0,351
183741,Programming? i love it!,92.0,146.0,1.0,ECUADOR,galocastillo,332.0,378
183742,WHAT???,255.0,73.0,17.0,ECUADOR,galocastillo,332.0,378
183743,Amazing video by Leonardo!,432.0,95.0,18.0,BRASIL,lucasperes,82.0,351
183744,Thanks man!,430.0,143.0,28.0,BRASIL,lucasperes,NaN,351
183745,There is nothing better than programming!,424.0,110.0,29.0,BRASIL,lucasperes,82.0,351
183746,BORED AF,488.0,28.0,27.0,MEXICO,gabrielcarvajal,21.0,2721
183747,I do not know if i like programming or other t...,318.0,58.0,20.0,BRASIL,isabelladasilva,928.0,9918

In [53]:
df[["full_text", "favorites"]]

                                                full_text  favorites
id
183721  Flying home to run down from the power to comi...       23.0
183722                Today we commemorate and MNML Case.      500.0
183723       Today we have reached US$6.55 Billion TT$44…      190.0
183724  Faking It by Joel Atwell. Written by Other cou...      131.0
183725                                    Welcome back! 🙌      113.0
183726  Contest: Win a fan of his ass. #thatisall Thanks!      492.0
183727                                 80's & friends! ✈️      158.0
183728  Thank you guess how did I feel somewhat offend...        NaN
183729        OnePlus 8 international giveaway classifies      198.0
183730                Here it is.. Retweet this desperate      272.0
183731  Great to advertise during the year I tweeted a...       43.0
183732  Its been in love with the game with the origin...      349.0
183733                           Programming is the best!      467.0
183734                             I cannot believe this!       50.0
183735                             Buy this product NOW!!      418.0
183736  I have one is best color gradients: Just relea...      361.0
183737                                              PIC!!      346.0
183738                             hmmm feeling bad today      296.0
183739                          not feeling god right now      315.0
183740                        Programming is a hot topic!      133.0
183741                            Programming? i love it!       92.0
183742                                            WHAT???      255.0
183743                         Amazing video by Leonardo!      432.0
183744                                        Thanks man!      430.0
183745          There is nothing better than programming!      424.0
183746                                           BORED AF      488.0
183747  I do not know if i like programming or other t...      318.0

In [59]:
df.iloc[0]
# df.iloc[0:3]
# df.iloc[[0, 2, 3]]
df.loc[[183745, 183723]]

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183745,There is nothing better than programming!,424.0,110.0,29.0,BRASIL,lucasperes,82.0,351
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129

In [61]:
df.loc[[183745, 183723], ["favorites"]]

        favorites
id
183745      424.0
183723      190.0

In [67]:
# df[df["favorites"] > 400]
# df[(df["favorites"] > 400 ) & (df["mentions"] > 20)]
df[df["full_text"].str.contains("Programming")]

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183733,Programming is the best!,467.0,69.0,10.0,ECUADOR,leonardokuffo,389.0,258
183740,Programming is a hot topic!,133.0,145.0,15.0,BRASIL,lucasperes,82.0,351
183741,Programming? i love it!,92.0,146.0,1.0,ECUADOR,galocastillo,332.0,378

In [81]:
import random
def calcularGanancias(retweets):
    return retweets * random.randint(3, 5)

df_filtrado["ganancias"] = df["retweets"].apply(calcularGanancias)

def popularidad(fila):
    resultado = fila['followees']/fila['followers']
    return resultado

df_filtrado['popularidad'] = df.apply(popularidad, axis=1)
df

,full_text,favorites,retweets,mentions,country,user,followers,followees,ganancias,popularidad
id,,,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,ECUADOR,leonardokuffo,389.0,258,NaN,0.663239
183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,BRASIL,mateusmartins,982.0,1822,105.0,1.855397
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129,369.0,10.750000
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378,380.0,1.138554
183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129,650.0,10.750000
183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,BRASIL,mateusmartins,982.0,1822,210.0,1.855397
183727,80's & friends! ✈️,158.0,40.0,22.0,ECUADOR,leonardokuffo,389.0,258,160.0,0.663239
183728,Thank you guess how did I feel somewhat offend...,NaN,50.0,10.0,MEXICO,pedrojuarez,12.0,129,150.0,10.750000
183729,OnePlus 8 international giveaway classifies,198.0,82.0,26.0,MEXICO,pedrojuarez,12.0,129,328.0,10.750000
183730,Here it is.. Retweet this desperate,272.0,92.0,29.0,BRASIL,mateusmartins,982.0,1822,368.0,1.855397
183731,Great to advertise during the year I tweeted a...,43.0,111.0,8.0,BRASIL,mateusmartins,982.0,1822,555.0,1.855397
183732,Its been in love with the game with the origin...,349.0,44.0,19.0,BRASIL,mateusmartins,982.0,1822,220.0,1.855397
183733,Programming is the best!,467.0,69.0,10.0,ECUADOR,leonardokuffo,389.0,258,345.0,0.663239
183734,I cannot believe this!,50.0,24.0,22.0,ECUADOR,leonardokuffo,389.0,258,96.0,0.663239
183735,Buy this product NOW!!,418.0,24.0,2.0,MEXICO,gabrielcarvajal,21.0,2721,96.0,129.571429
183736,I have one is best color gradients: Just relea...,361.0,92.0,1.0,MEXICO,pedrojuarez,12.0,129,368.0,10.750000
183737,PIC!!,346.0,115.0,24.0,BRASIL,lucasperes,82.0,351,575.0,4.280488
183738,hmmm feeling bad today,296.0,93.0,29.0,MEXICO,gabrielcarvajal,21.0,2721,465.0,129.571429
183739,not feeling god right now,315.0,26.0,10.0,ECUADOR,galocastillo,332.0,378,104.0,1.138554
183740,Programming is a hot topic!,133.0,145.0,15.0,BRASIL,lucasperes,82.0,351,580.0,4.280488
183741,Programming? i love it!,92.0,146.0,1.0,ECUADOR,galocastillo,332.0,378,438.0,1.138554
183742,WHAT???,255.0,73.0,17.0,ECUADOR,galocastillo,332.0,378,219.0,1.138554
183743,Amazing video by Leonardo!,432.0,95.0,18.0,BRASIL,lucasperes,82.0,351,285.0,4.280488
183744,Thanks man!,430.0,143.0,28.0,BRASIL,lucasperes,NaN,351,572.0,NaN
183745,There is nothing better than programming!,424.0,110.0,29.0,BRASIL,lucasperes,82.0,351,550.0,4.280488
183746,BORED AF,488.0,28.0,27.0,MEXICO,gabrielcarvajal,21.0,2721,84.0,129.571429
183747,I do not know if i like programming or other t...,318.0,58.0,20.0,BRASIL,isabelladasilva,928.0,9918,232.0,10.687500

In [86]:
df_filtrado.groupby("country").mean(numeric_only=True)

,favorites,retweets,mentions,followers,followees,ganancias,popularidad
country,,,,,,,
BRASIL,339.909091,91.272727,17.727273,616.600,1889.363636,344.000000,3.708644
ECUADOR,186.375000,56.750000,11.875000,360.500,318.000000,247.571429,0.900897
MEXICO,294.857143,77.750000,13.750000,15.375,1101.000000,291.375000,55.308036

In [87]:
df_filtrado.groupby("country").agg({
    "followers": 'sum',
    "mentions": 'mean',
    "retweets": 'max'
})

         followers   mentions  retweets
country
BRASIL      6166.0  17.727273     145.0
ECUADOR     2884.0  11.875000     146.0
MEXICO       123.0  13.750000     130.0